// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice =
  | ImageSlice
  | HeroSlice
  | FeaturedArticlesSlice
  | ImageSliderSlice
  | RelatedArticlesSlice
  | TextSlice
  | JellyLikesSlice
  | RelatedAnswersSlice
  | QuestionSlice
  | TestimonialsSlice
  | PullQuoteSlice
  | RecommendationsSlice
  | HeadlineSlice
  | SpacerSlice
  | DividingLineSlice
  | TeamMembersSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Headline field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: about us
   * - **API ID Path**: about.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Subheadline field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: the power of raw motherhood
   * - **API ID Path**: about.subheadline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Copy field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type AskJellyDocumentDataSlicesSlice =
  | ImageSlice
  | HeroSlice
  | FeaturedArticlesSlice
  | ImageSliderSlice
  | RelatedArticlesSlice
  | TeamMembersSlice
  | TextSlice
  | JellyLikesSlice
  | RelatedAnswersSlice
  | QuestionSlice
  | TestimonialsSlice
  | PullQuoteSlice
  | RecommendationsSlice
  | HeadlineSlice
  | SpacerSlice
  | DividingLineSlice;

/**
 * Content for Ask Jelly documents
 */
interface AskJellyDocumentData {
  /**
   * Headline field in *Ask Jelly*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Copy field in *Ask Jelly*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Slice Zone field in *Ask Jelly*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AskJellyDocumentDataSlicesSlice> /**
   * Meta Title field in *Ask Jelly*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ask_jelly.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Ask Jelly*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ask_jelly.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Ask Jelly*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * "Load More Articles" Button Text field in *Ask Jelly*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Load More
   * - **API ID Path**: ask_jelly.load_more_button_text
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  load_more_button_text: prismic.KeyTextField;

  /**
   * "No More Articles" Message field in *Ask Jelly*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No more articles to display.
   * - **API ID Path**: ask_jelly.no_more_articles_message
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_more_articles_message: prismic.KeyTextField;
}

/**
 * Ask Jelly document from Prismic
 *
 * - **API ID**: `ask_jelly`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AskJellyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AskJellyDocumentData>,
    "ask_jelly",
    Lang
  >;

type AskJellyArticleDocumentDataSlicesSlice =
  | HeroSlice
  | FeaturedArticlesSlice
  | RelatedArticlesSlice
  | TeamMembersSlice
  | TestimonialsSlice
  | PullQuoteSlice
  | RecommendationsSlice
  | SpacerSlice
  | JellyLikesSlice
  | RelatedAnswersSlice
  | QuestionSlice
  | ImageSlice
  | TextSlice
  | DividingLineSlice
  | HeadlineSlice
  | ImageSliderSlice;

/**
 * Content for Ask Jelly Article documents
 */
interface AskJellyArticleDocumentData {
  /**
   * Featured Image field in *Ask Jelly Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Article Title field in *Ask Jelly Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Asked By field in *Ask Jelly Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jenny C.
   * - **API ID Path**: ask_jelly_article.asked_by
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  asked_by: prismic.KeyTextField;

  /**
   * Author field in *Ask Jelly Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publication Date field in *Ask Jelly Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Slice Zone field in *Ask Jelly Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AskJellyArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Ask Jelly Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: ask_jelly_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Ask Jelly Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: ask_jelly_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Ask Jelly Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ask_jelly_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Ask Jelly Article document from Prismic
 *
 * - **API ID**: `ask_jelly_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AskJellyArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AskJellyArticleDocumentData>,
    "ask_jelly_article",
    Lang
  >;

type BlogDocumentDataSlicesSlice =
  | ImageSlice
  | FeaturedArticlesSlice
  | ImageSliderSlice
  | RelatedArticlesSlice
  | TeamMembersSlice
  | TextSlice
  | JellyLikesSlice
  | TestimonialsSlice
  | QuestionSlice
  | RelatedAnswersSlice
  | PullQuoteSlice
  | DividingLineSlice
  | RecommendationsSlice
  | HeadlineSlice
  | SpacerSlice
  | HeroSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * "Load More Articles" Button Text field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Load More
   * - **API ID Path**: blog.load_more_button_text
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  load_more_button_text: prismic.KeyTextField;

  /**
   * "No More Articles" Message field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No more articles to display.
   * - **API ID Path**: blog.no_more_articles_message
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_more_articles_message: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogArticleDocumentDataSlicesSlice =
  | FeaturedArticlesSlice
  | QuestionSlice
  | TestimonialsSlice
  | TeamMembersSlice
  | RelatedAnswersSlice
  | PullQuoteSlice
  | RecommendationsSlice
  | SpacerSlice
  | RelatedArticlesSlice
  | JellyLikesSlice
  | ImageSliderSlice
  | TextSlice
  | HeroSlice
  | ImageSlice
  | DividingLineSlice
  | HeadlineSlice;

/**
 * Content for Blog Article documents
 */
interface BlogArticleDocumentData {
  /**
   * Article Title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Author(s) field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publication Date field in *Blog Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Featured Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blog_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blog_article",
    Lang
  >;

/**
 * Item in *Contact → Contact Link*
 */
export interface ContactDocumentDataContactLinkItem {
  /**
   * Link Text field in *Contact → Contact Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_link[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Email Address field in *Contact → Contact Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contact@spreadthejelly.com
   * - **API ID Path**: contact.contact_link[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

type ContactDocumentDataSlicesSlice =
  | ImageSlice
  | HeroSlice
  | FeaturedArticlesSlice
  | ImageSliderSlice
  | TextSlice
  | TeamMembersSlice
  | RelatedArticlesSlice
  | JellyLikesSlice
  | TestimonialsSlice
  | QuestionSlice
  | DividingLineSlice
  | PullQuoteSlice
  | RelatedAnswersSlice
  | SpacerSlice
  | RecommendationsSlice
  | HeadlineSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Headline field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Copy field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.copy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Contact Link field in *Contact*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_link: prismic.GroupField<
    Simplify<ContactDocumentDataContactLinkItem>
  >;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Item in *Footer Links → Links*
 */
export interface FooterLinksDocumentDataLinksItem {
  /**
   * Label field in *Footer Links → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link Text
   * - **API ID Path**: footer_links.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Footer Links → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer Links documents
 */
interface FooterLinksDocumentData {
  /**
   * Links field in *Footer Links*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterLinksDocumentDataLinksItem>> /**
   * Facebook URL field in *Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.facebook_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  facebook_url: prismic.LinkField;

  /**
   * Instagram URL field in *Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.instagram_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_url: prismic.LinkField;

  /**
   * TikTok URL field in *Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.tiktok_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tiktok_url: prismic.LinkField;

  /**
   * YouTube URL field in *Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.youtube_url
   * - **Tab**: Social Links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_url: prismic.LinkField;
}

/**
 * Footer Links document from Prismic
 *
 * - **API ID**: `footer_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterLinksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterLinksDocumentData>,
    "footer_links",
    Lang
  >;

type JellyLovesDocumentDataSlicesSlice =
  | ImageSlice
  | FeaturedArticlesSlice
  | TeamMembersSlice
  | RelatedArticlesSlice
  | ImageSliderSlice
  | TextSlice
  | JellyLikesSlice
  | TestimonialsSlice
  | PullQuoteSlice
  | RelatedAnswersSlice
  | QuestionSlice
  | DividingLineSlice
  | RecommendationsSlice
  | HeadlineSlice
  | SpacerSlice
  | HeroSlice;

/**
 * Content for Jelly Loves documents
 */
interface JellyLovesDocumentData {
  /**
   * Slice Zone field in *Jelly Loves*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<JellyLovesDocumentDataSlicesSlice> /**
   * Meta Title field in *Jelly Loves*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: jelly_loves.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Jelly Loves*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: jelly_loves.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Jelly Loves*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * "Load More Articles" Button Text field in *Jelly Loves*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Load More
   * - **API ID Path**: jelly_loves.load_more_button_text
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  load_more_button_text: prismic.KeyTextField;

  /**
   * "No More Articles" Message field in *Jelly Loves*
   *
   * - **Field Type**: Text
   * - **Placeholder**: No more articles to display.
   * - **API ID Path**: jelly_loves.no_more_articles_message
   * - **Tab**: Blog Roll Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  no_more_articles_message: prismic.KeyTextField;
}

/**
 * Jelly Loves document from Prismic
 *
 * - **API ID**: `jelly_loves`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JellyLovesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<JellyLovesDocumentData>,
    "jelly_loves",
    Lang
  >;

type JellyLovesArticleDocumentDataSlicesSlice =
  | TestimonialsSlice
  | TeamMembersSlice
  | FeaturedArticlesSlice
  | QuestionSlice
  | RelatedAnswersSlice
  | PullQuoteSlice
  | SpacerSlice
  | RecommendationsSlice
  | ImageSlice
  | HeroSlice
  | RelatedArticlesSlice
  | ImageSliderSlice
  | TextSlice
  | JellyLikesSlice
  | DividingLineSlice
  | HeadlineSlice;

/**
 * Content for Jelly Loves Article documents
 */
interface JellyLovesArticleDocumentData {
  /**
   * Article Title field in *Jelly Loves Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Article Author field in *Jelly Loves Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Publication Date field in *Jelly Loves Article*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  publication_date: prismic.TimestampField;

  /**
   * Article Introduction field in *Jelly Loves Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.article_introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_introduction: prismic.RichTextField;

  /**
   * Featured Image field in *Jelly Loves Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Jelly Loves Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<JellyLovesArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Jelly Loves Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: jelly_loves_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Jelly Loves Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: jelly_loves_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Jelly Loves Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_loves_article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Jelly Loves Article document from Prismic
 *
 * - **API ID**: `jelly_loves_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JellyLovesArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<JellyLovesArticleDocumentData>,
    "jelly_loves_article",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Link Text
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Content for Newsletter Pop-Up Form documents
 */
interface NewsletterPopupFormDocumentData {
  /**
   * Headline field in *Newsletter Pop-Up Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Jelly
   * - **API ID Path**: newsletter_popup_form.headline
   * - **Tab**: Form Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Subheadline field in *Newsletter Pop-Up Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sign up for the newsletter
   * - **API ID Path**: newsletter_popup_form.subheadline
   * - **Tab**: Form Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Button Text field in *Newsletter Pop-Up Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Join the club!
   * - **API ID Path**: newsletter_popup_form.button_text
   * - **Tab**: Form Settings
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField /**
   * Success Headline field in *Newsletter Pop-Up Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Got it, thanks!
   * - **API ID Path**: newsletter_popup_form.success_headline
   * - **Tab**: Form Success Message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  success_headline: prismic.KeyTextField;

  /**
   * Success Subheadline field in *Newsletter Pop-Up Form*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_popup_form.success_subheadline
   * - **Tab**: Form Success Message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  success_subheadline: prismic.KeyTextField;
}

/**
 * Newsletter Pop-Up Form document from Prismic
 *
 * - **API ID**: `newsletter_popup_form`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsletterPopupFormDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NewsletterPopupFormDocumentData>,
    "newsletter_popup_form",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | RelatedAnswersSlice
  | SpacerSlice
  | RecommendationsSlice
  | RelatedArticlesSlice
  | FeaturedArticlesSlice
  | PullQuoteSlice
  | JellyLikesSlice
  | TestimonialsSlice
  | ImageSliderSlice
  | DividingLineSlice
  | QuestionSlice
  | ImageSlice
  | HeroSlice
  | HeadlineSlice
  | TeamMembersSlice
  | TextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: REVOLVE
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | AskJellyDocument
  | AskJellyArticleDocument
  | BlogDocument
  | BlogArticleDocument
  | ContactDocument
  | FooterLinksDocument
  | JellyLovesDocument
  | JellyLovesArticleDocument
  | NavigationDocument
  | NewsletterPopupFormDocument
  | PageDocument
  | SettingsDocument;

/**
 * Default variation for DividingLine Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividingLineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *DividingLine*
 */
type DividingLineSliceVariation = DividingLineSliceDefault;

/**
 * DividingLine Shared Slice
 *
 * - **API ID**: `dividing_line`
 * - **Description**: DividingLine
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividingLineSlice = prismic.SharedSlice<
  "dividing_line",
  DividingLineSliceVariation
>;

/**
 * Item in *FeaturedArticles → Default → Primary → Articles*
 */
export interface FeaturedArticlesSliceDefaultPrimaryArticlesItem {
  /**
   * Article field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.articles[].article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.ContentRelationshipField<
    "blog_article" | "jelly_loves_article" | "ask_jelly_article"
  >;

  /**
   * Article Title field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.articles[].article_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_title: prismic.KeyTextField;

  /**
   * Article Subtitle field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.articles[].article_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_subtitle: prismic.KeyTextField;

  /**
   * Featured Quote field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional! This will only appear if you select the "Featured Quote" card style.
   * - **API ID Path**: featured_articles.default.primary.articles[].featured_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featured_quote: prismic.KeyTextField;

  /**
   * Card Style field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full Bleed Image
   * - **API ID Path**: featured_articles.default.primary.articles[].card_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_style: prismic.SelectField<
    | "Full Bleed Image"
    | "Blob Mask 1"
    | "Blob Mask 2"
    | "Inset Image Vertical"
    | "Inset Image Horizontal"
    | "Featured Quote",
    "filled"
  >;

  /**
   * Card Background Color field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Black
   * - **API ID Path**: featured_articles.default.primary.articles[].card_bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_bg_color: prismic.SelectField<
    | "Black"
    | "White"
    | "Sunset"
    | "Ember"
    | "Soft Pink"
    | "Light Chartreuse"
    | "Sky Blue",
    "filled"
  >;

  /**
   * Card Hover Color field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Black
   * - **API ID Path**: featured_articles.default.primary.articles[].card_hover_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_hover_color: prismic.SelectField<
    | "Black"
    | "White"
    | "Sunset"
    | "Ember"
    | "Soft Pink"
    | "Light Chartreuse"
    | "Sky Blue",
    "filled"
  >;

  /**
   * Card Text Color field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: featured_articles.default.primary.articles[].card_text_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_text_color: prismic.SelectField<"White" | "Black", "filled">;

  /**
   * Card Text Align field in *FeaturedArticles → Default → Primary → Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Bottom
   * - **API ID Path**: featured_articles.default.primary.articles[].card_text_align
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_text_align: prismic.SelectField<"Bottom" | "Top", "filled">;
}

/**
 * Primary content in *FeaturedArticles → Default → Primary*
 */
export interface FeaturedArticlesSliceDefaultPrimary {
  /**
   * Articles field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.articles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<FeaturedArticlesSliceDefaultPrimaryArticlesItem>
  >;
}

/**
 * Default variation for FeaturedArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedArticles*
 */
type FeaturedArticlesSliceVariation = FeaturedArticlesSliceDefault;

/**
 * FeaturedArticles Shared Slice
 *
 * - **API ID**: `featured_articles`
 * - **Description**: FeaturedArticles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedArticlesSlice = prismic.SharedSlice<
  "featured_articles",
  FeaturedArticlesSliceVariation
>;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
  /**
   * Headline field in *Headline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Headline Level field in *Headline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: headline.default.primary.headline_level
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_level: prismic.SelectField<
    "h1" | "h2" | "h3" | "h4" | "h5" | "h6",
    "filled"
  >;

  /**
   * Headline Style field in *Headline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Large
   * - **API ID Path**: headline.default.primary.headline_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_style: prismic.SelectField<
    "Large" | "Medium" | "Small" | "Hidden",
    "filled"
  >;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<
  "headline",
  HeadlineSliceVariation
>;

/**
 * Item in *Hero → Bump → Primary → Headline*
 */
export interface HeroSliceDefaultPrimaryHeadlineItem {
  /**
   * Headline Text field in *Hero → Bump → Primary → Headline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.headline[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Headline Level field in *Hero → Bump → Primary → Headline*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: hero.default.primary.headline[].headline_level
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_level: prismic.SelectField<"h1" | "h2" | "p", "filled">;
}

/**
 * Item in *Hero → Straight → Primary → Headline*
 */
export interface HeroSliceStraightPrimaryHeadlineItem {
  /**
   * Headline Text field in *Hero → Straight → Primary → Headline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.straight.primary.headline[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Headline Level field in *Hero → Straight → Primary → Headline*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: hero.straight.primary.headline[].headline_level
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_level: prismic.SelectField<"h1" | "h2" | "p", "filled">;
}

/**
 * Item in *Hero → Super → Primary → Headline*
 */
export interface HeroSliceSuperPrimaryHeadlineItem {
  /**
   * Headline Text field in *Hero → Super → Primary → Headline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.headline[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Headline Level field in *Hero → Super → Primary → Headline*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: hero.super.primary.headline[].headline_level
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_level: prismic.SelectField<"h1" | "h2" | "p", "filled">;
}

/**
 * Item in *Hero → Vertical → Primary → Headline*
 */
export interface HeroSliceVerticalPrimaryHeadlineItem {
  /**
   * Headline Text field in *Hero → Vertical → Primary → Headline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.vertical.primary.headline[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Headline Level field in *Hero → Vertical → Primary → Headline*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h1
   * - **API ID Path**: hero.vertical.primary.headline[].headline_level
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  headline_level: prismic.SelectField<"h1" | "h2" | "p", "filled">;
}

/**
 * Primary content in *Hero → Bump → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Link (optional) field in *Hero → Bump → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Hero → Bump → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Headline field in *Hero → Bump → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.headline[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  headline: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryHeadlineItem>>;

  /**
   * Subheadline field in *Hero → Bump → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Call to Action (optional) field in *Hero → Bump → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add a short CTA like "read more", "find out why", etc.
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;
}

/**
 * Bump variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Straight → Primary*
 */
export interface HeroSliceStraightPrimary {
  /**
   * Link (optional) field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.straight.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.straight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.straight.primary.headline[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  headline: prismic.GroupField<Simplify<HeroSliceStraightPrimaryHeadlineItem>>;

  /**
   * Subheadline field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.straight.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Text Color field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White
   * - **API ID Path**: hero.straight.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_color: prismic.SelectField<"White" | "Black", "filled">;

  /**
   * Call to Action (optional) field in *Hero → Straight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add a short CTA like "read more", "find out why", etc.
   * - **API ID Path**: hero.straight.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;
}

/**
 * Straight variation for Hero Slice
 *
 * - **API ID**: `straight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceStraight = prismic.SharedSliceVariation<
  "straight",
  Simplify<HeroSliceStraightPrimary>,
  never
>;

/**
 * Primary content in *Hero → Super → Primary*
 */
export interface HeroSliceSuperPrimary {
  /**
   * Link (optional) field in *Hero → Super → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Hero → Super → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Headline field in *Hero → Super → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.headline[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  headline: prismic.GroupField<Simplify<HeroSliceSuperPrimaryHeadlineItem>>;

  /**
   * Subheadline field in *Hero → Super → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Copy field in *Hero → Super → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.super.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Call to Action (optional) field in *Hero → Super → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add a short CTA like "read more", "find out why", etc.
   * - **API ID Path**: hero.super.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;
}

/**
 * Super variation for Hero Slice
 *
 * - **API ID**: `super`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSuper = prismic.SharedSliceVariation<
  "super",
  Simplify<HeroSliceSuperPrimary>,
  never
>;

/**
 * Primary content in *Hero → Vertical → Primary*
 */
export interface HeroSliceVerticalPrimary {
  /**
   * Link (optional) field in *Hero → Vertical → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.vertical.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Hero → Vertical → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.vertical.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Headline field in *Hero → Vertical → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.vertical.primary.headline[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  headline: prismic.GroupField<Simplify<HeroSliceVerticalPrimaryHeadlineItem>>;

  /**
   * Subheadline field in *Hero → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.vertical.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Call to Action (optional) field in *Hero → Vertical → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Add a short CTA like "read more", "find out why", etc.
   * - **API ID Path**: hero.vertical.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;
}

/**
 * Vertical variation for Hero Slice
 *
 * - **API ID**: `vertical`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceVertical = prismic.SharedSliceVariation<
  "vertical",
  Simplify<HeroSliceVerticalPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceStraight
  | HeroSliceSuper
  | HeroSliceVertical;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Image → Three Column → Primary → Images (choose 3)*
 */
export interface ImageSliceThreeColumnPrimaryImagesItem {
  /**
   * Image field in *Image → Three Column → Primary → Images (choose 3)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.threeColumn.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Image → Grid → Primary → Images (choose 4)*
 */
export interface ImageSliceGridPrimaryImagesItem {
  /**
   * Image field in *Image → Grid → Primary → Images (choose 4)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.grid.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Image → Full-Width → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Full-Width → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Include Bump Mask? field in *Image → Full-Width → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.default.primary.include_mask
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  include_mask: prismic.BooleanField;
}

/**
 * Full-Width variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Two Column → Primary*
 */
export interface ImageSliceTwoColumnPrimary {
  /**
   * Image Left field in *Image → Two Column → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoColumn.primary.image_left
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_left: prismic.ImageField<never>;

  /**
   * Image Right field in *Image → Two Column → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.twoColumn.primary.image_right
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_right: prismic.ImageField<never>;
}

/**
 * Two Column variation for Image Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceTwoColumn = prismic.SharedSliceVariation<
  "twoColumn",
  Simplify<ImageSliceTwoColumnPrimary>,
  never
>;

/**
 * Primary content in *Image → Three Column → Primary*
 */
export interface ImageSliceThreeColumnPrimary {
  /**
   * Images (choose 3) field in *Image → Three Column → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.threeColumn.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ImageSliceThreeColumnPrimaryImagesItem>>;
}

/**
 * Three Column variation for Image Slice
 *
 * - **API ID**: `threeColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceThreeColumn = prismic.SharedSliceVariation<
  "threeColumn",
  Simplify<ImageSliceThreeColumnPrimary>,
  never
>;

/**
 * Primary content in *Image → Grid → Primary*
 */
export interface ImageSliceGridPrimary {
  /**
   * Images (choose 4) field in *Image → Grid → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.grid.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ImageSliceGridPrimaryImagesItem>>;
}

/**
 * Grid variation for Image Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceGrid = prismic.SharedSliceVariation<
  "grid",
  Simplify<ImageSliceGridPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation =
  | ImageSliceDefault
  | ImageSliceTwoColumn
  | ImageSliceThreeColumn
  | ImageSliceGrid;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *ImageSlider → Small Carousel → Primary → Images*
 */
export interface ImageSliderSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *ImageSlider → Small Carousel → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageSlider → Small Carousel → Primary*
 */
export interface ImageSliderSliceDefaultPrimary {
  /**
   * Headline (optional) field in *ImageSlider → Small Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Images field in *ImageSlider → Small Carousel → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slider.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliderSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Small Carousel variation for ImageSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageSlider*
 */
type ImageSliderSliceVariation = ImageSliderSliceDefault;

/**
 * ImageSlider Shared Slice
 *
 * - **API ID**: `image_slider`
 * - **Description**: ImageSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliderSlice = prismic.SharedSlice<
  "image_slider",
  ImageSliderSliceVariation
>;

/**
 * Item in *JellyLikes → Default → Primary → Products*
 */
export interface JellyLikesSliceDefaultPrimaryProductsItem {
  /**
   * Product Image field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Product Name field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_name: prismic.KeyTextField;

  /**
   * Product Manufacturer field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_manufacturer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_manufacturer: prismic.KeyTextField;

  /**
   * Product Info field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_info: prismic.KeyTextField;

  /**
   * Product Price field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  product_price: prismic.NumberField;

  /**
   * Product Link field in *JellyLikes → Default → Primary → Products*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[].product_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_link: prismic.LinkField;
}

/**
 * Primary content in *JellyLikes → Default → Primary*
 */
export interface JellyLikesSliceDefaultPrimary {
  /**
   * Who Likes? field in *JellyLikes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jelly Likes
   * - **API ID Path**: jelly_likes.default.primary.who_likes
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  who_likes: prismic.KeyTextField;

  /**
   * Products field in *JellyLikes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: jelly_likes.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<JellyLikesSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for JellyLikes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JellyLikesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JellyLikesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JellyLikes*
 */
type JellyLikesSliceVariation = JellyLikesSliceDefault;

/**
 * JellyLikes Shared Slice
 *
 * - **API ID**: `jelly_likes`
 * - **Description**: JellyLikes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JellyLikesSlice = prismic.SharedSlice<
  "jelly_likes",
  JellyLikesSliceVariation
>;

/**
 * Primary content in *PullQuote → Default → Primary*
 */
export interface PullQuoteSliceDefaultPrimary {
  /**
   * Quote field in *PullQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pull_quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * Quote Source field in *PullQuote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of article or source of the quote
   * - **API ID Path**: pull_quote.default.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;

  /**
   * Link (optional) field in *PullQuote → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to an article, file, or another website
   * - **API ID Path**: pull_quote.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for PullQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PullQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PullQuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PullQuote*
 */
type PullQuoteSliceVariation = PullQuoteSliceDefault;

/**
 * PullQuote Shared Slice
 *
 * - **API ID**: `pull_quote`
 * - **Description**: PullQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PullQuoteSlice = prismic.SharedSlice<
  "pull_quote",
  PullQuoteSliceVariation
>;

/**
 * Primary content in *Question → Default → Primary*
 */
export interface QuestionSliceDefaultPrimary {
  /**
   * Shape field in *Question → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: question.default.primary.shape
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  shape: prismic.ImageField<never>;

  /**
   * Question field in *Question → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: question.default.primary.question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.RichTextField;

  /**
   * Asked By field in *Question → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: from
   * - **API ID Path**: question.default.primary.asked_by
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  asked_by: prismic.KeyTextField;

  /**
   * Layout field in *Question → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Image Left
   * - **API ID Path**: question.default.primary.layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  layout: prismic.SelectField<"Image Left" | "Image Right", "filled">;
}

/**
 * Default variation for Question Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuestionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Question*
 */
type QuestionSliceVariation = QuestionSliceDefault;

/**
 * Question Shared Slice
 *
 * - **API ID**: `question`
 * - **Description**: Question
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuestionSlice = prismic.SharedSlice<
  "question",
  QuestionSliceVariation
>;

/**
 * Item in *Recommendations → Default → Primary → Recommendation*
 */
export interface RecommendationsSliceDefaultPrimaryRecommendationItem {
  /**
   * Image field in *Recommendations → Default → Primary → Recommendation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recommendations.default.primary.recommendation[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Recommendations → Default → Primary → Recommendation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommendations.default.primary.recommendation[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Copy field in *Recommendations → Default → Primary → Recommendation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommendations.default.primary.recommendation[].copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;
}

/**
 * Primary content in *Recommendations → Default → Primary*
 */
export interface RecommendationsSliceDefaultPrimary {
  /**
   * Recommendation field in *Recommendations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recommendations.default.primary.recommendation[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  recommendation: prismic.GroupField<
    Simplify<RecommendationsSliceDefaultPrimaryRecommendationItem>
  >;
}

/**
 * Default variation for Recommendations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecommendationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Recommendations*
 */
type RecommendationsSliceVariation = RecommendationsSliceDefault;

/**
 * Recommendations Shared Slice
 *
 * - **API ID**: `recommendations`
 * - **Description**: Recommendations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendationsSlice = prismic.SharedSlice<
  "recommendations",
  RecommendationsSliceVariation
>;

/**
 * Item in *RelatedAnswers → Default → Primary → Answers*
 */
export interface RelatedAnswersSliceDefaultPrimaryAnswersItem {
  /**
   * Answer field in *RelatedAnswers → Default → Primary → Answers*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: related_answers.default.primary.answers[].answer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  answer: prismic.ContentRelationshipField<"ask_jelly_article">;
}

/**
 * Primary content in *RelatedAnswers → Default → Primary*
 */
export interface RelatedAnswersSliceDefaultPrimary {
  /**
   * Answers field in *RelatedAnswers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: related_answers.default.primary.answers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  answers: prismic.GroupField<
    Simplify<RelatedAnswersSliceDefaultPrimaryAnswersItem>
  >;
}

/**
 * Default variation for RelatedAnswers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedAnswersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RelatedAnswersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RelatedAnswers*
 */
type RelatedAnswersSliceVariation = RelatedAnswersSliceDefault;

/**
 * RelatedAnswers Shared Slice
 *
 * - **API ID**: `related_answers`
 * - **Description**: RelatedAnswers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedAnswersSlice = prismic.SharedSlice<
  "related_answers",
  RelatedAnswersSliceVariation
>;

/**
 * Item in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
 */
export interface RelatedArticlesSliceDefaultPrimaryArticlesItem {
  /**
   * Article Link field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: related_articles.default.primary.articles[].article_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article_link: prismic.ContentRelationshipField<
    "blog_article" | "jelly_loves_article" | "ask_jelly_article"
  >;

  /**
   * Article Title field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_articles.default.primary.articles[].article_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_title: prismic.KeyTextField;

  /**
   * Article Subtitle field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: related_articles.default.primary.articles[].article_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_subtitle: prismic.KeyTextField;

  /**
   * Featured Quote field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional! This will only appear if you select the "Featured Quote" card style.
   * - **API ID Path**: related_articles.default.primary.articles[].featured_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featured_quote: prismic.KeyTextField;

  /**
   * Card Style field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full-Bleed Image
   * - **API ID Path**: related_articles.default.primary.articles[].card_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_style: prismic.SelectField<
    | "Full-Bleed Image"
    | "Blob Mask 1"
    | "Blob Mask 2"
    | "Inset Image Vertical"
    | "Inset Image Horizontal"
    | "Featured Quote",
    "filled"
  >;

  /**
   * Card Background Color field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Black
   * - **API ID Path**: related_articles.default.primary.articles[].card_bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_bg_color: prismic.SelectField<
    | "Black"
    | "White"
    | "Sunset"
    | "Ember"
    | "Soft Pink"
    | "Light Chartreuse"
    | "Sky Blue",
    "filled"
  >;

  /**
   * Card Hover Color field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Black
   * - **API ID Path**: related_articles.default.primary.articles[].card_hover_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_hover_color: prismic.SelectField<
    | "Black"
    | "White"
    | "Sunset"
    | "Ember"
    | "Soft Pink"
    | "Light Chartreuse"
    | "Sky Blue",
    "filled"
  >;

  /**
   * Card Text Color field in *RelatedArticles → Default → Primary → Related Articles (choose 3)*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Only applies to 'Featured Quote' card style
   * - **API ID Path**: related_articles.default.primary.articles[].card_text_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_text_color: prismic.SelectField<"White" | "Black">;
}

/**
 * Primary content in *RelatedArticles → Default → Primary*
 */
export interface RelatedArticlesSliceDefaultPrimary {
  /**
   * Headline (optional) field in *RelatedArticles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: You might also like
   * - **API ID Path**: related_articles.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Related Articles (choose 3) field in *RelatedArticles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: related_articles.default.primary.articles[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<RelatedArticlesSliceDefaultPrimaryArticlesItem>
  >;
}

/**
 * Default variation for RelatedArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RelatedArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RelatedArticles*
 */
type RelatedArticlesSliceVariation = RelatedArticlesSliceDefault;

/**
 * RelatedArticles Shared Slice
 *
 * - **API ID**: `related_articles`
 * - **Description**: RelatedArticles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelatedArticlesSlice = prismic.SharedSlice<
  "related_articles",
  RelatedArticlesSliceVariation
>;

/**
 * Primary content in *Spacer → Default → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Set the height of your spacer.
   * - **API ID Path**: spacer.default.primary.size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  size: prismic.SelectField<"Small" | "Medium" | "Large" | "XL">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Item in *TeamMembers → Default → Primary → Team Member*
 */
export interface TeamMembersSliceDefaultPrimaryTeamMemberItem {
  /**
   * Image field in *TeamMembers → Default → Primary → Team Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TeamMembers → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Bio field in *TeamMembers → Default → Primary → Team Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[].bio
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Social Link field in *TeamMembers → Default → Primary → Team Member*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[].social_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_link: prismic.LinkField;

  /**
   * Social Link Text field in *TeamMembers → Default → Primary → Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[].social_link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_link_text: prismic.KeyTextField;
}

/**
 * Primary content in *TeamMembers → Default → Primary*
 */
export interface TeamMembersSliceDefaultPrimary {
  /**
   * Team Member field in *TeamMembers → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_members.default.primary.team_member[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_member: prismic.GroupField<
    Simplify<TeamMembersSliceDefaultPrimaryTeamMemberItem>
  >;
}

/**
 * Default variation for TeamMembers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMembersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamMembersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamMembers*
 */
type TeamMembersSliceVariation = TeamMembersSliceDefault;

/**
 * TeamMembers Shared Slice
 *
 * - **API ID**: `team_members`
 * - **Description**: TeamMembers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamMembersSlice = prismic.SharedSlice<
  "team_members",
  TeamMembersSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Testimonial field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial: prismic.KeyTextField;

  /**
   * Credit field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jane, Miami
   * - **API ID Path**: testimonials.default.primary.testimonials[].credit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credit: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Headline (optional) field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Jelly Community
   * - **API ID Path**: testimonials.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *Copy → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Copy field in *Copy → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;
}

/**
 * Default variation for Copy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Copy → Copy with Image → Primary*
 */
export interface TextSliceCopyWithImagePrimary {
  /**
   * Image field in *Copy → Copy with Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Caption field in *Copy → Copy with Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithImage.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Copy field in *Copy → Copy with Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithImage.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Layout field in *Copy → Copy with Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithImage.primary.layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  layout: prismic.SelectField<"Image Left" | "Image Right">;
}

/**
 * Copy with Image variation for Copy Slice
 *
 * - **API ID**: `copyWithImage`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceCopyWithImage = prismic.SharedSliceVariation<
  "copyWithImage",
  Simplify<TextSliceCopyWithImagePrimary>,
  never
>;

/**
 * Primary content in *Copy → Copy with Pull Quote → Primary*
 */
export interface TextSliceCopyWithPullQuotePrimary {
  /**
   * Copy field in *Copy → Copy with Pull Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithPullQuote.primary.copy
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copy: prismic.RichTextField;

  /**
   * Pull Quote field in *Copy → Copy with Pull Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.copyWithPullQuote.primary.pull_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pull_quote: prismic.KeyTextField;

  /**
   * Pull Quote Position field in *Copy → Copy with Pull Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Quote Left
   * - **API ID Path**: text.copyWithPullQuote.primary.pull_quote_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  pull_quote_position: prismic.SelectField<
    "Quote Left" | "Quote Right",
    "filled"
  >;
}

/**
 * Copy with Pull Quote variation for Copy Slice
 *
 * - **API ID**: `copyWithPullQuote`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceCopyWithPullQuote = prismic.SharedSliceVariation<
  "copyWithPullQuote",
  Simplify<TextSliceCopyWithPullQuotePrimary>,
  never
>;

/**
 * Primary content in *Copy → Pull Quote → Primary*
 */
export interface TextSlicePullQuotePrimary {
  /**
   * Max Quote Width (in pixels) field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: The default is 800, but if your quote is short, you should lower it to force line breaks.
   * - **API ID Path**: text.pullQuote.primary.max_quote_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  max_quote_width: prismic.NumberField;

  /**
   * Pull Quote field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.pullQuote.primary.pull_quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pull_quote: prismic.KeyTextField;

  /**
   * Sticker Left (optional) field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Add a sticker. Or don't!
   * - **API ID Path**: text.pullQuote.primary.illustration_left
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_left: prismic.SelectField<
    | "Pink Flower"
    | "Yellow Flower"
    | "Blue Flower"
    | "Green Flower"
    | "Blue Star"
    | "Red Star"
    | "Green Star"
  >;

  /**
   * Sticker Left Position field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Set the vertical position of your sticker.
   * - **API ID Path**: text.pullQuote.primary.illustration_left_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_left_position: prismic.SelectField<"Top" | "Middle" | "Bottom">;

  /**
   * Sticker Right (optional) field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Add a sticker. Or don't!
   * - **API ID Path**: text.pullQuote.primary.illustration_right
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_right: prismic.SelectField<
    | "Pink Flower"
    | "Yellow Flower"
    | "Blue Flower"
    | "Green Flower"
    | "Blue Star"
    | "Red Star"
    | "Green Star"
  >;

  /**
   * Sticker Right Position field in *Copy → Pull Quote → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Set the vertical position of your sticker.
   * - **API ID Path**: text.pullQuote.primary.illustration_right_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  illustration_right_position: prismic.SelectField<"Top" | "Middle" | "Bottom">;
}

/**
 * Pull Quote variation for Copy Slice
 *
 * - **API ID**: `pullQuote`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlicePullQuote = prismic.SharedSliceVariation<
  "pullQuote",
  Simplify<TextSlicePullQuotePrimary>,
  never
>;

/**
 * Slice variation for *Copy*
 */
type TextSliceVariation =
  | TextSliceDefault
  | TextSliceCopyWithImage
  | TextSliceCopyWithPullQuote
  | TextSlicePullQuote;

/**
 * Copy Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      AskJellyDocument,
      AskJellyDocumentData,
      AskJellyDocumentDataSlicesSlice,
      AskJellyArticleDocument,
      AskJellyArticleDocumentData,
      AskJellyArticleDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataContactLinkItem,
      ContactDocumentDataSlicesSlice,
      FooterLinksDocument,
      FooterLinksDocumentData,
      FooterLinksDocumentDataLinksItem,
      JellyLovesDocument,
      JellyLovesDocumentData,
      JellyLovesDocumentDataSlicesSlice,
      JellyLovesArticleDocument,
      JellyLovesArticleDocumentData,
      JellyLovesArticleDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NewsletterPopupFormDocument,
      NewsletterPopupFormDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      DividingLineSlice,
      DividingLineSliceVariation,
      DividingLineSliceDefault,
      FeaturedArticlesSlice,
      FeaturedArticlesSliceDefaultPrimaryArticlesItem,
      FeaturedArticlesSliceDefaultPrimary,
      FeaturedArticlesSliceVariation,
      FeaturedArticlesSliceDefault,
      HeadlineSlice,
      HeadlineSliceDefaultPrimary,
      HeadlineSliceVariation,
      HeadlineSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryHeadlineItem,
      HeroSliceDefaultPrimary,
      HeroSliceStraightPrimaryHeadlineItem,
      HeroSliceStraightPrimary,
      HeroSliceSuperPrimaryHeadlineItem,
      HeroSliceSuperPrimary,
      HeroSliceVerticalPrimaryHeadlineItem,
      HeroSliceVerticalPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceStraight,
      HeroSliceSuper,
      HeroSliceVertical,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceTwoColumnPrimary,
      ImageSliceThreeColumnPrimaryImagesItem,
      ImageSliceThreeColumnPrimary,
      ImageSliceGridPrimaryImagesItem,
      ImageSliceGridPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceTwoColumn,
      ImageSliceThreeColumn,
      ImageSliceGrid,
      ImageSliderSlice,
      ImageSliderSliceDefaultPrimaryImagesItem,
      ImageSliderSliceDefaultPrimary,
      ImageSliderSliceVariation,
      ImageSliderSliceDefault,
      JellyLikesSlice,
      JellyLikesSliceDefaultPrimaryProductsItem,
      JellyLikesSliceDefaultPrimary,
      JellyLikesSliceVariation,
      JellyLikesSliceDefault,
      PullQuoteSlice,
      PullQuoteSliceDefaultPrimary,
      PullQuoteSliceVariation,
      PullQuoteSliceDefault,
      QuestionSlice,
      QuestionSliceDefaultPrimary,
      QuestionSliceVariation,
      QuestionSliceDefault,
      RecommendationsSlice,
      RecommendationsSliceDefaultPrimaryRecommendationItem,
      RecommendationsSliceDefaultPrimary,
      RecommendationsSliceVariation,
      RecommendationsSliceDefault,
      RelatedAnswersSlice,
      RelatedAnswersSliceDefaultPrimaryAnswersItem,
      RelatedAnswersSliceDefaultPrimary,
      RelatedAnswersSliceVariation,
      RelatedAnswersSliceDefault,
      RelatedArticlesSlice,
      RelatedArticlesSliceDefaultPrimaryArticlesItem,
      RelatedArticlesSliceDefaultPrimary,
      RelatedArticlesSliceVariation,
      RelatedArticlesSliceDefault,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
      TeamMembersSlice,
      TeamMembersSliceDefaultPrimaryTeamMemberItem,
      TeamMembersSliceDefaultPrimary,
      TeamMembersSliceVariation,
      TeamMembersSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceCopyWithImagePrimary,
      TextSliceCopyWithPullQuotePrimary,
      TextSlicePullQuotePrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceCopyWithImage,
      TextSliceCopyWithPullQuote,
      TextSlicePullQuote,
    };
  }
}
